#!/usr/bin/env bash
# Lists all running processes including TTY-less ones in a hierarchical format with correct headers

ps -eo user,lstart,cmd --forest | awk 'NR==1{$2="STARTED"; $3=$4=$5=$6=""; $0=$1" "$2" "$7} NR>1{$2=$3=$4=$5=$6=""; $0=$1" "$7" "$8; print}' | column -t
