#!/usr/bin/env bash
# Lists all running processes in tree format with required headers

ps -eo user,lstart,cmd --forest | awk 'NR==1 {print "USER STARTED CMD"; next} {started=$3" "$4" "$5" "$6" "$7; cmd=""; for(i=8;i<=NF;++i) cmd=cmd" "$i; print $1, started, cmd}'
